// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZxVxzCzuxzZUGzH0ZGhIHf2vAIyQjLI4',
    appId: '1:187010060007:android:27d1a1fd9cf606b9ea9c42',
    messagingSenderId: '187010060007',
    projectId: 'fir-orbital-app',
    databaseURL: 'https://fir-orbital-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-orbital-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3XavVBeSdPtOWeW7Ka5oRLuVnG0SH_9k',
    appId: '1:187010060007:ios:64acf0c2be739266ea9c42',
    messagingSenderId: '187010060007',
    projectId: 'fir-orbital-app',
    databaseURL: 'https://fir-orbital-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-orbital-app.appspot.com',
    iosClientId: '187010060007-slhl97v6qs94hojn4bgb3clbrs8sq98o.apps.googleusercontent.com',
    iosBundleId: 'com.example.orbitalApp',
  );
}
